//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 28.02.2014 21:32:51
namespace Client.JobService
{
    
    /// <summary>
    /// There are no comments for ListOfWorkersEntities in the schema.
    /// </summary>
    public partial class ListOfWorkersEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ListOfWorkersEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ListOfWorkersEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ListOfWorkersModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Client.JobService", typeName.Substring(18)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Client.JobService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ListOfWorkersModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Workman in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Workman> Workman
        {
            get
            {
                if ((this._Workman == null))
                {
                    this._Workman = base.CreateQuery<Workman>("Workman");
                }
                return this._Workman;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Workman> _Workman;
        /// <summary>
        /// There are no comments for PoliceList in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PoliceList> PoliceList
        {
            get
            {
                if ((this._PoliceList == null))
                {
                    this._PoliceList = base.CreateQuery<PoliceList>("PoliceList");
                }
                return this._PoliceList;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PoliceList> _PoliceList;
        /// <summary>
        /// There are no comments for Workman in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWorkman(Workman workman)
        {
            base.AddObject("Workman", workman);
        }
        /// <summary>
        /// There are no comments for PoliceList in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPoliceList(PoliceList policeList)
        {
            base.AddObject("PoliceList", policeList);
        }
    }
    /// <summary>
    /// There are no comments for ListOfWorkersModel.Workman in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PersonID")]
    public partial class Workman
    {
        /// <summary>
        /// Create a new Workman object.
        /// </summary>
        /// <param name="personID">Initial value of PersonID.</param>
        /// <param name="surnume">Initial value of Surnume.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="secondName">Initial value of SecondName.</param>
        /// <param name="dateOfBirth">Initial value of DateOfBirth.</param>
        /// <param name="position">Initial value of Position.</param>
        /// <param name="salary">Initial value of Salary.</param>
        /// <param name="expirience">Initial value of Expirience.</param>
        /// <param name="dateOfStart">Initial value of DateOfStart.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Workman CreateWorkman(int personID, string surnume, string name, string secondName, string dateOfBirth, string position, int salary, string expirience, string dateOfStart)
        {
            Workman workman = new Workman();
            workman.PersonID = personID;
            workman.Surnume = surnume;
            workman.Name = name;
            workman.SecondName = secondName;
            workman.DateOfBirth = dateOfBirth;
            workman.Position = position;
            workman.Salary = salary;
            workman.Expirience = expirience;
            workman.DateOfStart = dateOfStart;
            return workman;
        }
        /// <summary>
        /// There are no comments for Property PersonID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PersonID
        {
            get
            {
                return this._PersonID;
            }
            set
            {
                this.OnPersonIDChanging(value);
                this._PersonID = value;
                this.OnPersonIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PersonID;
        partial void OnPersonIDChanging(int value);
        partial void OnPersonIDChanged();
        /// <summary>
        /// There are no comments for Property Surnume in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surnume
        {
            get
            {
                return this._Surnume;
            }
            set
            {
                this.OnSurnumeChanging(value);
                this._Surnume = value;
                this.OnSurnumeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surnume;
        partial void OnSurnumeChanging(string value);
        partial void OnSurnumeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SecondName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecondName
        {
            get
            {
                return this._SecondName;
            }
            set
            {
                this.OnSecondNameChanging(value);
                this._SecondName = value;
                this.OnSecondNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecondName;
        partial void OnSecondNameChanging(string value);
        partial void OnSecondNameChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DateOfBirth;
        partial void OnDateOfBirthChanging(string value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Position;
        partial void OnPositionChanging(string value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Salary in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Salary
        {
            get
            {
                return this._Salary;
            }
            set
            {
                this.OnSalaryChanging(value);
                this._Salary = value;
                this.OnSalaryChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Salary;
        partial void OnSalaryChanging(int value);
        partial void OnSalaryChanged();
        /// <summary>
        /// There are no comments for Property Expirience in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Expirience
        {
            get
            {
                return this._Expirience;
            }
            set
            {
                this.OnExpirienceChanging(value);
                this._Expirience = value;
                this.OnExpirienceChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Expirience;
        partial void OnExpirienceChanging(string value);
        partial void OnExpirienceChanged();
        /// <summary>
        /// There are no comments for Property DateOfStart in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DateOfStart
        {
            get
            {
                return this._DateOfStart;
            }
            set
            {
                this.OnDateOfStartChanging(value);
                this._DateOfStart = value;
                this.OnDateOfStartChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DateOfStart;
        partial void OnDateOfStartChanging(string value);
        partial void OnDateOfStartChanged();
    }
    /// <summary>
    /// There are no comments for ListOfWorkersModel.PoliceList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PersonID")]
    public partial class PoliceList
    {
        /// <summary>
        /// Create a new PoliceList object.
        /// </summary>
        /// <param name="personID">Initial value of PersonID.</param>
        /// <param name="surnume">Initial value of Surnume.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="secondName">Initial value of SecondName.</param>
        /// <param name="dateOfBirth">Initial value of DateOfBirth.</param>
        /// <param name="crimeAction">Initial value of CrimeAction.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PoliceList CreatePoliceList(int personID, string surnume, string name, string secondName, string dateOfBirth, string crimeAction)
        {
            PoliceList policeList = new PoliceList();
            policeList.PersonID = personID;
            policeList.Surnume = surnume;
            policeList.Name = name;
            policeList.SecondName = secondName;
            policeList.DateOfBirth = dateOfBirth;
            policeList.CrimeAction = crimeAction;
            return policeList;
        }
        /// <summary>
        /// There are no comments for Property PersonID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PersonID
        {
            get
            {
                return this._PersonID;
            }
            set
            {
                this.OnPersonIDChanging(value);
                this._PersonID = value;
                this.OnPersonIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PersonID;
        partial void OnPersonIDChanging(int value);
        partial void OnPersonIDChanged();
        /// <summary>
        /// There are no comments for Property Surnume in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surnume
        {
            get
            {
                return this._Surnume;
            }
            set
            {
                this.OnSurnumeChanging(value);
                this._Surnume = value;
                this.OnSurnumeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surnume;
        partial void OnSurnumeChanging(string value);
        partial void OnSurnumeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SecondName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecondName
        {
            get
            {
                return this._SecondName;
            }
            set
            {
                this.OnSecondNameChanging(value);
                this._SecondName = value;
                this.OnSecondNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecondName;
        partial void OnSecondNameChanging(string value);
        partial void OnSecondNameChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DateOfBirth;
        partial void OnDateOfBirthChanging(string value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property CrimeAction in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CrimeAction
        {
            get
            {
                return this._CrimeAction;
            }
            set
            {
                this.OnCrimeActionChanging(value);
                this._CrimeAction = value;
                this.OnCrimeActionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CrimeAction;
        partial void OnCrimeActionChanging(string value);
        partial void OnCrimeActionChanged();
    }
}
