//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BusinesObj
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ListOfWorkersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ListOfWorkersEntities object using the connection string found in the 'ListOfWorkersEntities' section of the application configuration file.
        /// </summary>
        public ListOfWorkersEntities() : base("name=ListOfWorkersEntities", "ListOfWorkersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ListOfWorkersEntities object.
        /// </summary>
        public ListOfWorkersEntities(string connectionString) : base(connectionString, "ListOfWorkersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ListOfWorkersEntities object.
        /// </summary>
        public ListOfWorkersEntities(EntityConnection connection) : base(connection, "ListOfWorkersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Workman> Workman
        {
            get
            {
                if ((_Workman == null))
                {
                    _Workman = base.CreateObjectSet<Workman>("Workman");
                }
                return _Workman;
            }
        }
        private ObjectSet<Workman> _Workman;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PoliceList> PoliceList
        {
            get
            {
                if ((_PoliceList == null))
                {
                    _PoliceList = base.CreateObjectSet<PoliceList>("PoliceList");
                }
                return _PoliceList;
            }
        }
        private ObjectSet<PoliceList> _PoliceList;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workman EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkman(Workman workman)
        {
            base.AddObject("Workman", workman);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PoliceList EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPoliceList(PoliceList policeList)
        {
            base.AddObject("PoliceList", policeList);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ListOfWorkersModel", Name="PoliceList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PoliceList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PoliceList object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="surnume">Initial value of the Surnume property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="secondName">Initial value of the SecondName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="crimeAction">Initial value of the CrimeAction property.</param>
        public static PoliceList CreatePoliceList(global::System.Int32 personID, global::System.String surnume, global::System.String name, global::System.String secondName, global::System.String dateOfBirth, global::System.String crimeAction)
        {
            PoliceList policeList = new PoliceList();
            policeList.PersonID = personID;
            policeList.Surnume = surnume;
            policeList.Name = name;
            policeList.SecondName = secondName;
            policeList.DateOfBirth = dateOfBirth;
            policeList.CrimeAction = crimeAction;
            return policeList;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                if (_PersonID != value)
                {
                    OnPersonIDChanging(value);
                    ReportPropertyChanging("PersonID");
                    _PersonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonID");
                    OnPersonIDChanged();
                }
            }
        }
        private global::System.Int32 _PersonID;
        partial void OnPersonIDChanging(global::System.Int32 value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Surnume
        {
            get
            {
                return _Surnume;
            }
            set
            {
                OnSurnumeChanging(value);
                ReportPropertyChanging("Surnume");
                _Surnume = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Surnume");
                OnSurnumeChanged();
            }
        }
        private global::System.String _Surnume;
        partial void OnSurnumeChanging(global::System.String value);
        partial void OnSurnumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondName
        {
            get
            {
                return _SecondName;
            }
            set
            {
                OnSecondNameChanging(value);
                ReportPropertyChanging("SecondName");
                _SecondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondName");
                OnSecondNameChanged();
            }
        }
        private global::System.String _SecondName;
        partial void OnSecondNameChanging(global::System.String value);
        partial void OnSecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.String _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.String value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrimeAction
        {
            get
            {
                return _CrimeAction;
            }
            set
            {
                OnCrimeActionChanging(value);
                ReportPropertyChanging("CrimeAction");
                _CrimeAction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CrimeAction");
                OnCrimeActionChanged();
            }
        }
        private global::System.String _CrimeAction;
        partial void OnCrimeActionChanging(global::System.String value);
        partial void OnCrimeActionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ListOfWorkersModel", Name="Workman")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Workman : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Workman object.
        /// </summary>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="surnume">Initial value of the Surnume property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="secondName">Initial value of the SecondName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="salary">Initial value of the Salary property.</param>
        /// <param name="expirience">Initial value of the Expirience property.</param>
        /// <param name="dateOfStart">Initial value of the DateOfStart property.</param>
        public static Workman CreateWorkman(global::System.Int32 personID, global::System.String surnume, global::System.String name, global::System.String secondName, global::System.String dateOfBirth, global::System.String position, global::System.Int32 salary, global::System.String expirience, global::System.String dateOfStart)
        {
            Workman workman = new Workman();
            workman.PersonID = personID;
            workman.Surnume = surnume;
            workman.Name = name;
            workman.SecondName = secondName;
            workman.DateOfBirth = dateOfBirth;
            workman.Position = position;
            workman.Salary = salary;
            workman.Expirience = expirience;
            workman.DateOfStart = dateOfStart;
            return workman;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                if (_PersonID != value)
                {
                    OnPersonIDChanging(value);
                    ReportPropertyChanging("PersonID");
                    _PersonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonID");
                    OnPersonIDChanged();
                }
            }
        }
        private global::System.Int32 _PersonID;
        partial void OnPersonIDChanging(global::System.Int32 value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Surnume
        {
            get
            {
                return _Surnume;
            }
            set
            {
                OnSurnumeChanging(value);
                ReportPropertyChanging("Surnume");
                _Surnume = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Surnume");
                OnSurnumeChanged();
            }
        }
        private global::System.String _Surnume;
        partial void OnSurnumeChanging(global::System.String value);
        partial void OnSurnumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondName
        {
            get
            {
                return _SecondName;
            }
            set
            {
                OnSecondNameChanging(value);
                ReportPropertyChanging("SecondName");
                _SecondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondName");
                OnSecondNameChanged();
            }
        }
        private global::System.String _SecondName;
        partial void OnSecondNameChanging(global::System.String value);
        partial void OnSecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.String _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.String value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private global::System.Int32 _Salary;
        partial void OnSalaryChanging(global::System.Int32 value);
        partial void OnSalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Expirience
        {
            get
            {
                return _Expirience;
            }
            set
            {
                OnExpirienceChanging(value);
                ReportPropertyChanging("Expirience");
                _Expirience = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Expirience");
                OnExpirienceChanged();
            }
        }
        private global::System.String _Expirience;
        partial void OnExpirienceChanging(global::System.String value);
        partial void OnExpirienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateOfStart
        {
            get
            {
                return _DateOfStart;
            }
            set
            {
                OnDateOfStartChanging(value);
                ReportPropertyChanging("DateOfStart");
                _DateOfStart = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateOfStart");
                OnDateOfStartChanged();
            }
        }
        private global::System.String _DateOfStart;
        partial void OnDateOfStartChanging(global::System.String value);
        partial void OnDateOfStartChanged();

        #endregion

    
    }

    #endregion

    
}
